# Generated by Django 5.0.6 on 2024-06-08 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_overs_timeline_ball1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player_match_stats',
            name='player_name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='player_match_stats',
            name='strike_rate',
            field=models.FloatField(db_default=0),
        ),
        migrations.AlterField(
            model_name='player_match_stats',
            name='team_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='player_match_stats',
            name='username',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='player_stats',
            name='bowling_average',
            field=models.FloatField(db_default=0),
        ),
        migrations.AlterField(
            model_name='player_stats',
            name='economy',
            field=models.FloatField(db_default=0),
        ),
        migrations.AlterField(
            model_name='player_stats',
            name='first_name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='player_stats',
            name='last_name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='player_stats',
            name='password',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='player_stats',
            name='strike_rate',
            field=models.FloatField(db_default=0),
        ),
        migrations.AlterField(
            model_name='player_stats',
            name='username',
            field=models.CharField(max_length=250),
        ),
    ]
